import { getSession, useSession, signOut } from 'next-auth/react';

import Head from 'next/head';
import { getToken } from 'next-auth/jwt';

export default function Account({ token }) {
  const { data: session } = useSession();
  const tokenUser = token?.token?.user?.email;

  if (!session) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        {console.log(session)}
        {session && (
          <>
            Signed in as {tokenUser} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
      </div>

    </>
  );
}

export async function getServerSideProps(context) {
  const { req, res } = context;
  const session = await getSession({ req });

  if (!session) {
    res.setHeader("location", "/login");
    res.statusCode = 302;
    res.end();
    return;
  }

  const token = await getToken({ req, secret: process.env.NEXTAUTH_JWT_SECRET });

  return {
    props: { token }
  };
}
